### ISSUE TITLE
Search: indexing files full-text

### ISSUE THREAD

**Issue by MarcoKlerks** [GPP-Woo/GPP-zoeken#12]
Alleen machineleesbare tekst in een bestand kan geïndexeerd worden. We passen bijvoorbeeld geen [OCR](https://nl.wikipedia.org/wiki/Optical_character_recognition) toe om woorden uit afbeeldingen te herkennen.

**Acceptatie criteria**

- In #10 wordt informatie aangeleverd over de vindplaats van het bestand (bijv. PDF) behorende bij een document. Dit bestand wordt opgehaald.
- Het bestand wordt geïndexeerd, zodat later gezocht kan worden op woorden in het bestand (full-text search).
- Ook grote bestanden kunnen opgehaald worden. 
- Relevantie (enkele richtinggevende uitspraken):  
   - Wanneer woorden in een metadata-veld voorkomen dan is dit relevanter dan wanneer ze in het bestand voorkomen.

--------------------------------------------
_Copied form #7:_ 
Elastic Search has a built in module/feature to index the contents of PDFs/Spreadsheets, which you can enable in processing pipelines.

Ref: https://www.elastic.co/guide/en/elasticsearch/reference/8.15/attachment.html

**Tasks**

- [x] Ensure an attachment processor is pre-configured
- [ ] Ensure the attachment processor is used on supported document types
- [x] Ensure (some) tuning parameters can be specified as envvars
- [x] Document system requirements, recommendation of a dedicated node
- [x] Document that gpp-zoeken needs read access/credentials to gpp-publicatiebank to download the file
- [ ] See if we can set up a multi-node docker-compose (nice to have)
- [x] gpp-publicatiebank needs to send the download URL + file size

**Comment by sergei-maertens** [comment]
> zodat hier ook het bestand aangeboden kan worden.

zoals opgemerkt bij de publicatiebank willen we de richting hier omdraaien en zoeken laten pullen/downloaden ipv de bestanden erheen pushen/uploaden.

**Comment by MarcoKlerks** [comment]
@sergei-maertens Ik heb de story aangepast, zodat de richting wordt omgedraaid. Zie ook #10 . Controleer even of de "size" (story points) nog steeds passend is.

**Comment by sergei-maertens** [comment]
prima zo - bij het inschatten gingen we al uit van deze correctie :wink:
