### ISSUE TITLE
Search: index the contents of published documents

### ISSUE THREAD

**Issue by sergei-maertens** [GPP-Woo/GPP-zoeken#7]
Elastic Search has a built in module/feature to index the contents of PDFs/Spreadsheets, which you can enable in processing pipelines.

Ref: https://www.elastic.co/guide/en/elasticsearch/reference/8.15/attachment.html

**Tasks**

- [ ] Ensure an attachment processor is pre-configured
- [ ] Ensure the attachment processor is used on supported document types
- [ ] Ensure (some) tuning parameters can be specified as envvars
- [ ] Document system requirements, recommendation of a dedicated node
- [ ] See if we can set up a multi-node docker-compose (nice to have)
